// Suggestion catalog for profile autocomplete. Static, no network.
// `value` is what gets inserted; `aliases` only help matching.

export interface CatalogItem {
  value: string;
  aliases?: string[];
}

const r = (value: string, ...aliases: string[]): CatalogItem => ({ value, aliases });

export const ROLES: CatalogItem[] = [
  // Software
  r("Frontend Developer", "front end", "фронтенд", "fe dev"),
  r("Frontend Engineer"),
  r("Backend Developer", "back end", "бэкенд", "be dev"),
  r("Backend Engineer"),
  r("Fullstack Developer", "full stack", "фулстек"),
  r("Fullstack Engineer"),
  r("Software Engineer", "swe", "программист"),
  r("Software Developer"),
  r("Web Developer", "веб-разработчик"),
  r("React Developer", "reactjs"),
  r("Vue.js Developer", "vue developer"),
  r("Angular Developer"),
  r("Next.js Developer", "nextjs"),
  r("Node.js Developer", "nodejs"),
  r("TypeScript Developer", "ts developer"),
  r("JavaScript Developer", "js developer"),
  r("Python Developer", "питон"),
  r("Java Developer", "java разработчик"),
  r("Kotlin Developer"),
  r("Go Developer", "golang developer"),
  r("Rust Developer"),
  r("C# Developer", ".net developer", "dotnet developer"),
  r("C++ Developer"),
  r("PHP Developer", "laravel developer"),
  r("Ruby on Rails Developer", "rails developer"),
  r("Mobile Developer", "мобильный разработчик"),
  r("iOS Developer", "swift developer"),
  r("Android Developer"),
  r("Flutter Developer", "dart developer"),
  r("React Native Developer"),
  r("Game Developer", "unity developer", "unreal developer"),
  r("Embedded Engineer", "embedded developer"),
  r("Blockchain Developer", "web3 developer", "solidity developer"),
  r("QA Engineer", "tester", "тестировщик", "quality assurance"),
  r("QA Automation Engineer", "sdet", "automation tester"),
  r("DevOps Engineer", "девопс"),
  r("Site Reliability Engineer", "sre"),
  r("Platform Engineer"),
  r("Cloud Engineer", "aws engineer"),
  r("Security Engineer", "infosec", "information security"),
  r("Penetration Tester", "pentester"),
  r("Systems Administrator", "sysadmin", "системный администратор"),
  r("Network Engineer", "сетевой инженер"),
  r("Database Administrator", "dba"),
  r("Solutions Architect", "software architect"),
  r("Technical Lead", "tech lead", "team lead", "тимлид"),
  r("Engineering Manager"),
  r("CTO", "chief technology officer"),
  // Data / AI
  r("Data Analyst", "аналитик данных"),
  r("Data Scientist"),
  r("Data Engineer"),
  r("Machine Learning Engineer", "ml engineer"),
  r("AI Engineer", "llm engineer"),
  r("Prompt Engineer"),
  r("BI Analyst", "business intelligence"),
  r("Analytics Engineer"),
  r("Computer Vision Engineer"),
  r("NLP Engineer"),
  // Product / design
  r("Product Manager", "pm", "продакт-менеджер"),
  r("Product Owner", "po"),
  r("Project Manager", "проектный менеджер"),
  r("Scrum Master", "agile coach"),
  r("Business Analyst", "ba", "бизнес-аналитик"),
  r("System Analyst", "системный аналитик"),
  r("UI/UX Designer", "ux designer", "ui designer", "product designer", "дизайнер"),
  r("Graphic Designer", "графический дизайнер"),
  r("Motion Designer"),
  r("3D Artist"),
  r("Technical Writer", "технический писатель"),
  // Business
  r("Marketing Manager", "маркетолог"),
  r("Digital Marketing Specialist", "performance marketing"),
  r("SEO Specialist", "seo"),
  r("SMM Manager", "smm", "social media manager"),
  r("Content Manager", "контент-менеджер"),
  r("Copywriter", "копирайтер"),
  r("Sales Manager", "менеджер по продажам"),
  r("Account Manager"),
  r("Customer Support Specialist", "support manager", "служба поддержки"),
  r("Customer Success Manager"),
  r("HR Manager", "recruiter", "рекрутер"),
  r("Talent Acquisition Specialist"),
  r("Accountant", "бухгалтер"),
  r("Financial Analyst", "финансовый аналитик"),
  r("Operations Manager"),
  r("Logistics Manager", "логист"),
  r("Translator", "переводчик"),
  r("Office Manager", "офис-менеджер"),
  r("Administrator", "администратор"),
  r("Junior Developer", "junior"),
  r("Intern", "стажер", "стажёр", "trainee"),
];

export const SKILLS: CatalogItem[] = [
  // Languages
  r("JavaScript", "js", "ecmascript"),
  r("TypeScript", "ts"),
  r("Python", "py"),
  r("Java"),
  r("Kotlin"),
  r("Swift"),
  r("Go", "golang"),
  r("Rust"),
  r("C#", "csharp", "c sharp"),
  r("C++", "cpp"),
  r("C"),
  r("PHP"),
  r("Ruby"),
  r("Scala"),
  r("Dart"),
  r("SQL"),
  r("Bash", "shell scripting"),
  r("HTML", "html5"),
  r("CSS", "css3"),
  // Frontend
  r("React", "reactjs", "react.js"),
  r("Next.js", "nextjs"),
  r("Vue.js", "vue", "vuejs"),
  r("Nuxt", "nuxt.js"),
  r("Angular"),
  r("Svelte", "sveltekit"),
  r("Redux", "redux toolkit"),
  r("Zustand"),
  r("MobX"),
  r("React Query", "tanstack query"),
  r("Tailwind CSS", "tailwind"),
  r("SASS", "scss"),
  r("Styled Components"),
  r("Material UI", "mui"),
  r("Webpack"),
  r("Vite"),
  r("Storybook"),
  r("Framer Motion"),
  r("Three.js"),
  // Backend
  r("Node.js", "node", "nodejs"),
  r("Express", "express.js"),
  r("NestJS", "nest.js"),
  r("Fastify"),
  r("Django"),
  r("Flask"),
  r("FastAPI"),
  r("Spring Boot", "spring"),
  r("Laravel"),
  r("Symfony"),
  r("ASP.NET", ".net", "dotnet"),
  r("Ruby on Rails", "rails"),
  r("GraphQL", "apollo"),
  r("REST API", "restful", "rest"),
  r("gRPC"),
  r("WebSocket", "websockets", "socket.io"),
  r("Microservices"),
  r("tRPC"),
  // Data
  r("PostgreSQL", "postgres"),
  r("MySQL"),
  r("MongoDB", "mongo"),
  r("Redis"),
  r("Elasticsearch", "elk"),
  r("ClickHouse"),
  r("SQLite"),
  r("Prisma"),
  r("TypeORM"),
  r("Kafka", "apache kafka"),
  r("RabbitMQ"),
  r("Pandas"),
  r("NumPy"),
  r("Spark", "apache spark", "pyspark"),
  r("Airflow", "apache airflow"),
  r("dbt"),
  r("Tableau"),
  r("Power BI", "powerbi"),
  r("Excel", "ms excel"),
  r("Machine Learning", "ml"),
  r("Deep Learning"),
  r("PyTorch"),
  r("TensorFlow"),
  r("scikit-learn", "sklearn"),
  r("LLM", "large language models"),
  r("LangChain"),
  r("RAG", "retrieval augmented generation"),
  r("OpenAI API"),
  // DevOps / cloud
  r("Docker"),
  r("Kubernetes", "k8s"),
  r("Terraform"),
  r("Ansible"),
  r("AWS", "amazon web services"),
  r("Google Cloud", "gcp"),
  r("Azure"),
  r("Linux"),
  r("Nginx"),
  r("CI/CD", "cicd", "continuous integration"),
  r("GitHub Actions"),
  r("GitLab CI"),
  r("Jenkins"),
  r("Prometheus"),
  r("Grafana"),
  r("Git"),
  r("Vercel"),
  r("Cloudflare"),
  // Testing
  r("Jest"),
  r("Vitest"),
  r("Playwright"),
  r("Cypress"),
  r("Selenium"),
  r("Testing Library", "rtl"),
  r("Postman"),
  r("JUnit"),
  r("Pytest"),
  // Mobile
  r("React Native"),
  r("Flutter"),
  r("SwiftUI"),
  r("Jetpack Compose"),
  r("Firebase"),
  // Design / product
  r("Figma"),
  r("Sketch"),
  r("Adobe Photoshop", "photoshop"),
  r("Adobe Illustrator", "illustrator"),
  r("UX Research"),
  r("Wireframing"),
  r("Jira"),
  r("Confluence"),
  r("Scrum"),
  r("Kanban"),
  r("Agile"),
  // Business
  r("SEO"),
  r("Google Analytics", "ga4"),
  r("Google Ads"),
  r("CRM", "amocrm", "bitrix24"),
  r("1C", "1с"),
  // Enterprise & Russian Market Skills
  r("1C:Enterprise", "1c", "1с:предприятие", "1с", "1c:бухгалтерия", "1с:зуп"),
  r("Bitrix24", "битрикс", "bitrix", "1с-битрикс"),
  r("Тестирование ПО", "manual testing", "ручное тестирование", "регрессионное тестирование"),
  r("Техническая поддержка", "helpdesk", "техническая поддержка пользователей"),
  r("Составление ТЗ", "техническое задание", "разработка регламентов"),
  r("Анализ бизнес-процессов", "bpmn", "uml", "моделирование процессов"),
  r("Управление проектами", "project management", "scrum", "kanban"),
  r("Яндекс.Метрика", "yandex metrika", "яндекс метрика"),
  r("Яндекс.Директ", "yandex direct", "директ"),
  r("Деловая переписка", "деловое общение"),
  r("Бухгалтерский учет", "бухучет", "налоговый учет"),
  r("B2B Продажи", "b2b", "прямые продажи"),
];

export const KEYWORDS_RU: CatalogItem[] = [
  r("Фронтенд-разработчик", "frontend", "front", "фронтенд"),
  r("Бэкенд-разработчик", "backend", "back", "бэкенд"),
  r("Fullstack-разработчик", "fullstack", "фулстек"),
  r("Разработчик 1С", "1с программист", "программист 1с", "1c"),
  r("Разработчик", "developer", "dev"),
  r("Программист", "programmer"),
  r("Веб-разработчик", "web developer"),
  r("Python-разработчик", "python", "питон"),
  r("Java-разработчик", "java"),
  r("JavaScript-разработчик", "javascript", "js"),
  r("React-разработчик", "react"),
  r("Node.js-разработчик", "node", "nodejs"),
  r("Golang-разработчик", "go", "golang"),
  r("C#-разработчик", ".net", "csharp"),
  r("C++ разработчик", "cpp"),
  r("Мобильный разработчик", "mobile", "ios", "android"),
  r("Тестировщик ПО", "qa", "tester", "инженер по тестированию"),
  r("Автоматизатор тестирования", "qa automation", "автотесты"),
  r("DevOps-инженер", "devops", "девопс"),
  r("Системный администратор", "sysadmin", "администратор linux"),
  r("Сетевой инженер", "network engineer"),
  r("Инженер по безопасности", "infosec", "информационная безопасность"),
  r("Аналитик данных", "data analyst"),
  r("Дата-сайентист", "data scientist", "машинное обучение"),
  r("Инженер данных", "data engineer"),
  r("Бизнес-аналитик", "business analyst"),
  r("Системный аналитик", "system analyst"),
  r("Продакт-менеджер", "product manager", "управление продуктом"),
  r("Проектный менеджер", "project manager", "руководитель проектов"),
  r("UX/UI дизайнер", "designer", "дизайнер интерфейсов"),
  r("Технический писатель", "technical writer", "документация"),
  r("Менеджер по продажам", "sales", "менеджер b2b"),
  r("Интернет-маркетолог", "marketing", "маркетолог"),
  r("Специалист технической поддержки", "support", "поддержка", "helpdesk"),
  r("Удалённая работа", "remote", "удаленно", "дистанционно"),
  r("Гибридный график", "hybrid", "гибрид"),
  r("Стажёр", "intern", "стажер", "практикант"),
  r("Junior разработчик", "junior", "младший разработчик"),
  r("Middle разработчик", "middle"),
  r("Без опыта", "no experience", "для начинающих"),
];

export const EXCLUDE_KEYWORDS: CatalogItem[] = [
  r("PHP"), r("1C", "1с"), r("Bitrix", "битрикс"), r("WordPress"),
  r("jQuery"), r("Senior"), r("Lead"), r("Team Lead"), r("10+ years"),
  r("5+ years"), r("Office only"), r("Relocation required"),
  r("Sales"), r("Cold calling"), r("Call center", "колл-центр"),
  r("Internship unpaid"), r("Freelance"), r("Part-time"),
  r("Gambling", "казино"), r("Crypto trading"), r("Network marketing", "сетевой маркетинг"),
];

export const RED_FLAG_KEYWORDS: CatalogItem[] = [
  r("deposit", "залог"),
  r("unpaid test task", "бесплатное тестовое задание"),
  r("pay for training", "оплатите обучение"),
  r("send passport scan", "скан паспорта"),
  r("SMS code", "код из смс"),
  r("cold calling", "холодные звонки"),
  r("commission only", "только процент"),
  r("MLM", "сетевой маркетинг"),
  r("unlimited income", "неограниченный доход"),
  r("no contract", "без оформления"),
  r("work in Telegram only", "работа в телеграм"),
  r("urgent hiring no interview", "без собеседования"),
];
